# Generated by Django 4.2.1 on 2023-05-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема обращения')),
                ('textAppeal', models.TextField(verbose_name='Обращение')),
            ],
        ),
    ]
